language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: a0Qb+VnR7eMsjSn5K/OI+VdspZYQkmbPvWqRv6GFHOYS1FN4cmWprpboOS2lKLFY1nkjUi78oN1nr+8hgKR/PnRbI5DWy2ofTm733rNHFBsDGl/XCdvyYUkTOh1SYhay5/efPjspXriap83vW5XRI8q7XiCTjlIR5i9JDJQXmkNNJVbJsfCPD5q3r+eioESKu51W3+XoUC2MR84fURfjH8i1LSw9QU9IhYqpZnglXWt+AfotJGTEQyjgxmyh8sAMScoE16mLw2EpZ4ITbwY6HQjZ7o1qgOlpBDXYF8bNqPw3h5X2/KP98osC1EVs8zUzI9Pdqw9EBu9plzINfNDTCUaXmMItX3Ryhbx7/g2us90xA4SclyMAd2ecT+4bWSVeqVId/4vd3zpkXchGgOnRBeYJwHQswH6Hmymx8nMc86q8UFcc3bbrO/cdQf30GKBADPNSFAGpdw+Um7OQp1A+OCAa4l9q9XyTiuU1DWY71f1QFb4a1bnBk/2T/YS93t3dRXMHGCWn6rtt/SR7S/houg32IXVvhv+wvvs6939QF+uXUbz6B1iareL0Pxk0c7R/N0YS+VNGavFKTj1Vyx1XyZE+6liew71/1X/C+IyH0umUNLUqX0llId/f10VCecgmZqh6cMT5liNdA/Jqt412GF9V9jDSghxTF7nRljrQWg0=
