language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: DMcIxELErsvu1qLbCK8p5u2XHEGFKVDvrBG2Z1yIr27Mt6V5eVjIXf6U3vVxCyoK2Od9bEJazHZ6oE0puFOfZo2Xu1OBPMTFaQujCp6V2AnVkdPRdaGHW76Lz2X4LBJna4IMydlySMeVwVvooCqw/JHMZ9XXX/6j6G/8kI+HYhwHV8UTyIefz+UvgvCzWjka43hxMJYNVWEZDgxWyUwcCQbWQNIDMSclwJIxF6388GP8hmgOZlKVC10BheGczYMOu+26KYXruysvxN2Gs69zKdRJRJEmfIDML2AzPshCM9QtRrWDHXZk4In541bpDYkNVB6Gt5takX+4OIzzcXp7X5EEN1c8M7Qd1lBAw3gLko+e59ivtxo1vXbgtDOb8TmvpqPXymPWz8mqE7vdqvtRoAKdUqZ0ZncNQuwFmCRfEnq2kcPhTcXcgjR2z9yBBUHaaUfuGvgIXXyoXc3Hw5Mt7KgssWLwrih+tPDyoTmqhl3+7GokiSmGWjAR2/0pJcm9bamwuh63dhotbC+/uFOopuaPclxm2S2QpTl/6yhPZY3ablg61BQrqZJYhdi54uImDsmx5WRq2MNwFViX9/QnD7Iq+0gDIgYb/rO1DJKQzNDM1oB5mF43H+yPJ393tpm3kRUk/2jDIlIVngbX0SoP6OxUydYVqvt+PS0+gcWbxU0=
